-- MySQL Script generated by MySQL Workbench
-- Wed Mar 27 19:36:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionarios` (
  `ID` INT(5) NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dependencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dependencias` (
  `ID` INT(5) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  `administrador` INT(5) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Dependencias_Funcionarios_idx` (`administrador` ASC) VISIBLE,
  CONSTRAINT `fk_Dependencias_Funcionarios`
    FOREIGN KEY (`administrador`)
    REFERENCES `mydb`.`Funcionarios` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `ID` INT(5) NOT NULL AUTO_INCREMENT,
  `cuenta` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `rol` INT(2) NOT NULL,
  `funcionario` INT(5) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `cuenta_UNIQUE` (`cuenta` ASC) VISIBLE,
  INDEX `fk_Usuarios_Funcionarios1_idx` (`funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Funcionarios1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `mydb`.`Funcionarios` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Solicitudes` (
  `ID` INT(5) NOT NULL AUTO_INCREMENT,
  `comprobante` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `tipo` INT(1) NOT NULL,
  `cantidad` INT(5) NULL,
  `total` FLOAT NULL,
  `estado` INT(2) NOT NULL,
  `dependencia` INT(5) NOT NULL,
  `registrador` INT(5) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Solicitudes_Dependencias1_idx` (`dependencia` ASC) VISIBLE,
  INDEX `fk_Solicitudes_Funcionarios1_idx` (`registrador` ASC) VISIBLE,
  UNIQUE INDEX `comprobante_UNIQUE` (`comprobante` ASC) VISIBLE,
  CONSTRAINT `fk_Solicitudes_Dependencias1`
    FOREIGN KEY (`dependencia`)
    REFERENCES `mydb`.`Dependencias` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitudes_Funcionarios1`
    FOREIGN KEY (`registrador`)
    REFERENCES `mydb`.`Funcionarios` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bienes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bienes` (
  `ID` INT(5) NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` FLOAT NOT NULL,
  `cantidad` INT(5) NOT NULL,
  `solicitud` INT(5) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Bienes_Solicitudes1_idx` (`solicitud` ASC) VISIBLE,
  CONSTRAINT `fk_Bienes_Solicitudes1`
    FOREIGN KEY (`solicitud`)
    REFERENCES `mydb`.`Solicitudes` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Puestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Puestos` (
  `ID` INT(5) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `funcionario` INT(5) NULL,
  `dependencia` INT(5) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Puestos_Dependencias1_idx` (`dependencia` ASC) VISIBLE,
  INDEX `fk_Puestos_Funcionarios1_idx` (`funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_Puestos_Dependencias1`
    FOREIGN KEY (`dependencia`)
    REFERENCES `mydb`.`Dependencias` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Puestos_Funcionarios1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `mydb`.`Funcionarios` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Activos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Activos` (
  `ID` INT(5) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `puesto` INT(5) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  INDEX `fk_Activos_Puestos1_idx` (`puesto` ASC) VISIBLE,
  CONSTRAINT `fk_Activos_Puestos1`
    FOREIGN KEY (`puesto`)
    REFERENCES `mydb`.`Puestos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into Funcionarios(identificacion,nombre) values(403013010,"Oscar Campos");
insert into Funcionarios(identificacion,nombre) values(104294103,"Gabriel Jimenez");
insert into Funcionarios(identificacion,nombre) values(204030103,"Jose Quiroz");
insert into Funcionarios(identificacion,nombre) values(304014014,"Josue Ramirez");
insert into Funcionarios(identificacion,nombre) values(550240204,"Daniel Ortega");
insert into Funcionarios(identificacion,nombre) values(634203014,"Bryan Ruiz");
insert into Funcionarios(identificacion,nombre) values(421421412,"Jose Sanchez");
insert into Funcionarios(identificacion,nombre) values(532523523,"Marta Quriroz");
insert into Funcionarios(identificacion,nombre) values(532525276,"Oscar Ortega");
insert into Funcionarios(identificacion,nombre) values(421412423,"Felipe Ruiz");

insert into Dependencias(nombre,ubicacion,administrador) values('Escuela de informatica','Lagunilla-Heredia',1);
insert into Dependencias(nombre,ubicacion,administrador) values('Escuela de matematica','Heredia Centro',NULL);


insert into Puestos(nombre,funcionario,dependencia) values ("Administrador de la dependencia",1,1);
insert into Puestos(nombre,funcionario,dependencia) values ("Secretaria de la OCCB", 2,1);
insert into Puestos(nombre,funcionario,dependencia) values ("Jefe de la OCCB", 3,1);
insert into Puestos(nombre,funcionario,dependencia) values ("Registrador de bienes", 4,1);
insert into Puestos(nombre,funcionario,dependencia) values ("Registrador de bienes", 9,1);
insert into Puestos(nombre,funcionario,dependencia) values ("Registrador de bienes", 8,1);
insert into Puestos(nombre,funcionario,dependencia) values ("Jefe de RRHH", 7,1 );
insert into Puestos(nombre,funcionario,dependencia)  values ("Jefe de RRHH Y OCCB", 6,1);
insert into Puestos(nombre,funcionario,dependencia)  values ("Profesor Arqui", 10,1 );
insert into Puestos(nombre,funcionario,dependencia)  values ("Conserje", 8,1 );
insert into Puestos(nombre,funcionario,dependencia)  values ("Profesor sistemas operativos", null,1 );
insert into Puestos(nombre,funcionario,dependencia)  values ("Contador", null ,1 );
insert into Puestos(nombre,funcionario,dependencia)  values ("Profesor de redes", null ,1 );


insert into Usuarios(cuenta,password,rol,funcionario) values("admin_info","aaa",1,1);
insert into Usuarios(cuenta,password,rol,funcionario)  values("secretaria_info","bbb",2,2);
insert into Usuarios(cuenta,password,rol,funcionario)  values("jefe_OCCB","ccc",3,3);
insert into Usuarios(cuenta,password,rol,funcionario)  values("registrador1","rrr",4,4);
insert into Usuarios(cuenta,password,rol,funcionario) values("registrador2","rrr",4,5);
insert into Usuarios(cuenta,password,rol,funcionario) values("registrador3","rrr",4,6);
insert into Usuarios(cuenta,password,rol,funcionario)  values("jefe_RRHH","ddd",5,7);
insert into Usuarios(cuenta,password,rol,funcionario) values("jefe_OCCB_RRHH","ddd",7,8);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
